
#Deploys dev dependencies in sdk to prod
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /App
COPY . ./
RUN dotnet build -c Release

ENTRYPOINT ["dotnet", "run", "-c", "Release", "--no-build"]