apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test-helloworld
  name: test-helloworld
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-helloworld
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-helloworld
    spec:
      containers:
      - image: harbor.alemana.cl/dev/nuevaimagen@sha256:36c23d067cceffdd035971431a350740a4964432292b8d73240c15d0913076e0 
        name: nuevaimagena
        resources: {}
status: {}
