apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: test-helloworld
  name: test-helloworld-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: test-helloworld
  type: NodePort
status:
  loadBalancer: {}
